language: csharp

dist: trusty

sudo: required

mono: none

sudo: required

services:
  - docker

#branches:
#  only:
#    - master
#    - develop


#after_success:
#  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#  - docker tag publictransport:develop $DOCKER_USERNAME/publictransport:develop
#  - docker push $DOCKER_USERNAME/publictransport:develop
  
  
notifications:
  email:
    on_success: never
    on_failure: never


script:
  - pwd
  - docker build -f ./src/N2L.PublicTransport.API/Dockerfile -t publictransport:develop .